src/account/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from account import views


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'survey.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index,name="index"),
    url(r'^login/$', views.login,name="login"),
    url(r'^logout/$', views.logout,name="logout"),
)

src/japanese/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from japanese import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.japanese_index,name="japanese_index"),
)

src/jpclass/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from jpclass import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index,name="index"),
#    url(r'^submit/$', views.submit,name="submit"),
    url(r'^result/$', views.result,name="result"),
)

src/score/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from score import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'survey.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name="index"),
    url(r'^submit/$',views.submit,name="submit"),
    url(r'^result/$',views.result,name="result"),
)

src/survey/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'survey.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^stationary/', include('stationary.urls',namespace='stationary')),
    url(r'^account/', include('account.urls',namespace='account')),
    url(r'^japanese/', include('japanese.urls',namespace='japanese')),
    )

src/japanese/models.py
#-*- coding: UTF-8 -*- 
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import smart_text


class Ngrade(models.Model):
    grade = models.CharField(unique=True, max_length=5)
    def __unicode__(self):
        return self.grade
    
class Jpclass(models.Model):
    ngrade = models.ForeignKey(Ngrade)
    classname = models.CharField(max_length=20)
    
    def __unicode__(self):
        return smart_text('Classname:%s %s' % (self.classname, self.ngrade))
    
class JpclassAdmin(admin.ModelAdmin):
    list_display = ('id', 'ngrade', 'classname')
    list_filter = ['ngrade']

class Jpclasssubmit(models.Model):
    user = models.ForeignKey(User)
    jpclass = models.ForeignKey(Jpclass)
    def __unicode__(self):
        return smart_text('%s has signed up  %s' % (self.user, self.jpclass))
    
class JpclasssubmitAdmin(admin.ModelAdmin):
    list_display = ('id', 'user', 'jpclass')
    search_fields = ['user']


class Examdate(models.Model):
    month = models.IntegerField()
    year = models.IntegerField()
    def __unicode__(self):
        return smart_text('%s %s' % (str(self.month), str(self.year)))


class Examsignup(models.Model):
    user=models.ForeignKey(User)
    ngrade = models.ForeignKey(Ngrade)
    examdate = models.ForeignKey(Examdate)
    def __unicode__(self):
        return smart_text('%s %s %s' % (self.user, self.examdate, self.ngrade))

class ExamsignupAdmin(admin.ModelAdmin):
    list_display = ('id', 'ngrade', 'examdate', 'examdate')
    list_filter = ['ngrade']
    
class Examscore(models.Model):
    examsignup = models.ForeignKey(Examsignup)
    vocabulary = models.IntegerField(default=0)
    reading = models.IntegerField(default=0)
    grammar = models.IntegerField(default=0)
    def __unicode__(self):
        return smart_text('%s vocabulary_score:%i reading_score:%i grammer_score:%i' % (self.examsignup, self.vocabulary, self.reading, self.grammar))
    
class ExamscoreAdmin(admin.ModelAdmin):
    list_display = ('examsignup', 'vocabulary', 'reading', 'grammar')
        
admin.site.register(Examscore, ExamscoreAdmin)

admin.site.register(Examdate)
admin.site.register(Examsignup, ExamsignupAdmin)

admin.site.register(Ngrade)
admin.site.register(Jpclass, JpclassAdmin)
admin.site.register(Jpclasssubmit, JpclasssubmitAdmin)

src/jpclass/models.py
#-*- coding: UTF-8 -*- 
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import smart_text


class Ngrade(models.Model):
    grade = models.CharField(unique=True, max_length=5)
    def __unicode__(self):
        return self.grade
    
class Jpclass(models.Model):
    ngrade = models.ForeignKey(Ngrade)
    classname = models.CharField(max_length=10)
    
    def __unicode__(self):
        return smart_text('Classname:%s %s' % (self.classname, self.ngrade))
    
class JpclassAdmin(admin.ModelAdmin):
    list_display = ('id', 'ngrade', 'classname')
    list_filter = ['ngrade']

class Jpclasssubmit(models.Model):
    user = models.ForeignKey(User)
    jpclass = models.ForeignKey(Jpclass)
    def __unicode__(self):
        return smart_text('%s has signed up  %s' % (self.user, self.jpclass))
    
class JpclasssubmitAdmin(admin.ModelAdmin):
    list_display = ('id', 'user', 'jpclass')
    search_fields = ['user']

admin.site.register(Ngrade)
admin.site.register(Jpclass, JpclassAdmin)
admin.site.register(Jpclasssubmit, JpclasssubmitAdmin)

src/japanese/views.py
import json
from django.core import serializers
from django.contrib.auth.models import User
from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from japanese.models import Ngrade, Jpclass, Jpclasssubmit, Examsignup, Examdate
from japanese.models import Examscore
from django.core.exceptions import ObjectDoesNotExist

#jpclass
def get_context(request):
    u = request.user
    if Jpclasssubmit.objects.filter(user = u) :
        tempjs = Jpclasssubmit.objects.get(user = u)
    else:
        tempjs = None;
    gradedata = serializers.serialize('json', Ngrade.objects.all())
    classdata = serializers.serialize('json', Jpclass.objects.all())
    context = {'user':request.user, 'user_jpclasssubmit':tempjs, 'ngrade':Ngrade.objects.all(),'jpclass':Jpclass.objects.all(),'gradestr':gradedata,'classstr':classdata,'examdate':Examdate.objects.all(),'signup':Examsignup.objects.all(),'score':Examscore.objects.all()}
    return context

def japanese_index(request):
    if request.method =='POST':
        if request.POST['function'] == 'jpclass_submit':
            return jpclass_submit(request)
        if request.POST['function'] == 'jpclass_clear':
            return jpclass_clear(request)
        if request.POST['function'] == 'signup_submit':
            return signup_submit(request)
        if request.POST['function'] == 'score_submit':
            return score_submit(request)
    else:
        deleteid=request.GET.get("signupdeleteid")
        if deleteid:
            return signup_delete(request,deleteid)
        deleteid=request.GET.get("scoredeleteid")
        if deleteid:
            return score_delete(request,deleteid)

    context = get_context(request)    
    return render(request, 'japanese/index.html', context)

def jpclass_submit(request):
    try:
        #turn received KV into model Jpclass
        tempngrade = Ngrade.objects.get(id = request.POST['ngradeid'])
        tempjpclass = Jpclass.objects.get(id = request.POST['jpclassid'],ngrade = tempngrade )
        context = get_context(request)
    except ObjectDoesNotExist:
        context['error_message']="wrong input."
        return render(request, 'japanese/index.html',context)
    else:
        u = request.user
        if Jpclasssubmit.objects.filter(user = u) :
            Jpclasssubmit.objects.get(user = u).delete()
        #save data
        u.jpclasssubmit_set.create(jpclass = tempjpclass)
        return HttpResponseRedirect(reverse('japanese:japanese_index'))

def jpclass_clear(request):
    u = request.user
    if Jpclasssubmit.objects.filter(user = u) :
        Jpclasssubmit.objects.get(user = u).delete()
    return HttpResponseRedirect(reverse('japanese:japanese_index'))
#signup
def signup_submit(request):
    try:
        ngrade=Ngrade.objects.get(pk = request.POST['grade'])
        date=Examdate.objects.get(pk = request.POST['date'])
        u = request.user
        if Examsignup.objects.filter(user=u,ngrade = ngrade,examdate = date):
            Examsignup.objects.get(user=u,ngrade = ngrade,examdate = date).delete()
    except(ObjectDoesNotExist):
        context = get_context(request)
        context['error_message']="wrong input"
        return render(request, 'japanese/index.html', context)
    else:
        u.examsignup_set.create(ngrade = ngrade, examdate=date)
        return HttpResponseRedirect(reverse('japanese:japanese_index'))

def signup_delete(request,id):
    try:
        tempsignup=Examsignup.objects.get(pk = id,user = request.user)
        Examscore.objects.get(examsignup = tempsignup).delete()
        Examsignup.objects.get(pk = id,user = request.user).delete()
        
    except(ObjectDoesNotExist):
        context = get_context(request)
        context['error_message']="delete failed."
        return render(request, 'japanese/index.html',context)
    else:
        return HttpResponseRedirect(reverse('japanese:japanese_index'))

#score

def score_submit(request):
    try:
        context = get_context(request)
        v = request.POST['vocabulary']
        r = request.POST['reading']
        g = request.POST['grammar']
        tempsignup = Examsignup.objects.get(id=request.POST['signup'])
        if not (v.isdigit() and r.isdigit() and g.isdigit()):
            context['error_message']="You've inputed something wrong."
            return render(request,'japanese/index.html',context)
        tempv=int(v)
        tempr=int(r)
        tempg=int(g)
        if tempv<0 or tempv>100 :
            context['error_message']="Vocabulary_score out of range! "
            return render(request,'japanese/index.html',context)
        if tempr<0 or tempr>100 :
            context['error_message']="Reading_score out of range!"
            return render(request,'japanese/index.html',context)
        if tempg<0 or tempg>100 :
            context['error_message']="Grammar_score out of range!"
            return render(request,'japanese/index.html',context)
        if Examscore.objects.filter(examsignup=tempsignup):
            Examscore.objects.get(examsignup=tempsignup).delete()
    except(ObjectDoesNotExist):
        context['error_message']="ObjectDoesNotExist"
        return render(request,'japanese/index.html',context)
    else:
        tempsignup.examscore_set.create(vocabulary = tempv, reading = tempr, grammar = tempg)
        return HttpResponseRedirect(reverse('japanese:japanese_index'))

def score_delete(request,id):
    try:
        tempsignup=Examsignup.objects.get(pk = id,user = request.user)
        Examscore.objects.get(examsignup = tempsignup).delete()
    except(ObjectDoesNotExist):
        context = get_context(request)
        context['error_message']="delete failed."
        return render(request, 'japanese/index.html',context)
    else:
        return HttpResponseRedirect(reverse('japanese:japanese_index'))

src/jpclass/views.py
import json
from django.core import serializers
from django.contrib.auth.models import User
from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from jpclass.models import Ngrade, Jpclass, Jpclasssubmit
from django.core.exceptions import ObjectDoesNotExist

def index(request):
    if request.method =='POST':
        if request.POST['function'] == 'submit':
            return submit(request)
        if request.POST['function'] == 'clear':
            return clear(request)
    u = request.user
    if Jpclasssubmit.objects.filter(user = u) :
        tempjs = Jpclasssubmit.objects.get(user = u)
    else:
        tempjs = None;
    gradedata = serializers.serialize('json', Ngrade.objects.all())
    classdata = serializers.serialize('json', Jpclass.objects.all())
    context = {'user':request.user, 'user_jpclasssubmit':tempjs, 'ngrade':Ngrade.objects.all(),'jpclass':Jpclass.objects.all(),'gradestr':gradedata,'classstr':classdata}
    return render(request, 'jpclass/index.html', context)

def submit(request):
    try:
        #turn received KV into model Jpclass
        tempngrade = Ngrade.objects.get(id = request.POST['ngradeid'])
        tempjpclass = Jpclass.objects.get(id = request.POST['jpclassid'],ngrade = tempngrade )
    except ObjectDoesNotExist:
        return render(request, 'jpclass/index.html',{'error_message':"wrong input.", 'user':request.user, 'ngrade':Ngrade.objects.all(),'jpclass':Jpclass.objects.all()})
    else:
        u = request.user
        if Jpclasssubmit.objects.filter(user = u) :
            Jpclasssubmit.objects.get(user = u).delete()
        #save data
        u.jpclasssubmit_set.create(jpclass = tempjpclass)
        return HttpResponseRedirect(reverse('jpclass:index'))

def clear(request):
    u = request.user
    if Jpclasssubmit.objects.filter(user = u) :
        Jpclasssubmit.objects.get(user = u).delete()
    return HttpResponseRedirect(reverse('jpclass:index'))

def result(request):
    return render(request, 'jpclass/result.html', {'user':request.user, 'user_jpclasssubmit':Jpclasssubmit.objects.get(user = request.user)})

src/japanese/templates/jpclass/base.html
<html>
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}"/>
	<script src="{% static "js/jquery-2.1.0.min.js" %}"></script>
	<script src="{% static "js/bootstrap.min.js" %}"></script>
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<form action="{% url 'account:logout' %}" method="post">
		{% block user %}欢迎用户：{{user.username}}{% endblock %}
		{% csrf_token %} 
		<input type="submit" value="Logout" />
	</form>
	{% block content %}{% endblock %}
</body>
</html>

src/japanese/templates/jpclass/index.html
{% extends "jpclass/base.html" %}
{% block title %}Insert title here{% endblock %}
{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="row">
	<div class="col-lg-8">
		<div class="panel panel-primary" style="margin:50px">
			<div class="panel-heading">
				<h3 class="panel-title">Japanese Class</h3>
			</div>
			<div class="panel-body">
				<div id="resultrow" class="row">
					<div class="col-lg-4">
						<label id="levellabel" style="margin-top: 5px; margin-left: 10px; margin-bottom: 0px;"> Level:</label>
					</div>
					<div class="col-lg-4">
						<label id="classlabel" style="margin-top: 5px; margin-left: 10px; margin-bottom: 0px;"> Class:</label>
					</div>
					<div class="col-lg-2">
						<button id="changebtn" type="button" class="btn btn-primary btn-block" >Change</button>
					</div>
					<div class="col-lg-2">
						<form action="{% url 'japanese:jpclass_index' %}" method="post" style="margin-bottom:0px">
							{% csrf_token %}
							<button id="clearbtn" type="submit" name="function" value="clear" class="btn btn-danger btn-block" >Clear</button>
						</form>
					</div>
				</div>
				<div id="selectrow" class="row" style="display:none">
					<form action="{% url 'japanese:jpclass_index' %}" method="post">
						{% csrf_token %}
						<div class="col-lg-4">
							<select id="selectngrade" name="ngradeid" class="form-control" placeholder=".col-lg-1">
							</select>
						</div>
						<div class="col-lg-4">
							<select id="selectclass" name="jpclassid" class="form-control" placeholder=".col-lg-2">
							</select>
						</div>
						<div class="col-lg-2">
							<button id="submitbtn" name="function" value="submit" type="submit" class="btn btn-primary btn-block" >Submit</button>
						</div>
						<div class="col-lg-2">
							<button id="cancelbtn" type="button" class="btn btn-default btn-block">Cancel</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<span id ="gradestr" style="display:none">{{ gradestr }}</span>
<span id ="classstr" style="display:none">{{ classstr }}</span>
<span id ="user_jpclasssubmit" style="display:none">{{ user_jpclasssubmit }}</span>
<script>

if ($("#user_jpclasssubmit").text() == "None") {
	$("#levellabel").text("Level:None");
	$("#classlabel").text("Class:None");
}
else{
	$("#levellabel").text("Level:{{ user_jpclasssubmit.jpclass.ngrade }}");
	$("#classlabel").text("Class:{{ user_jpclasssubmit.jpclass.classname }}");
	
	
}

var gradestr = $("#gradestr").text();
var gradejson = $.parseJSON( gradestr );
var ngrade = new Array();
var i = 0;

$.each(gradejson, function(i,object){
	var tempk = "";
	$.each(object,function(item,value){
		tempk = this['grade'];
	});
	ngrade[i++]={id:this['pk'], grade:tempk};
});

for (var i = 0; i < ngrade.length; i++) {
	$("<option>").val(ngrade[i].id).text(ngrade[i].grade).appendTo('#selectngrade');
};

if($("#user_jpclasssubmit").text() != "None"){
	$(document).ready(function() {
		$("#selectngrade option[value={{ user_jpclasssubmit.jpclass.ngrade.id }}]").attr('selected', 'selected');
	});
}

var classstr = $("#classstr").text();
var classjson = $.parseJSON( classstr );
var classes = new Array();
i = 0;
$.each(classjson, function(i,object){
	var tempc = "";
	var tempg = "";
	$.each(object,function(item,value){
		tempc = this['classname'];
		tempg = this['ngrade'];
	});
	classes[i++]={id:this['pk'],classname:tempc,ngrade:tempg};
});

$(document).ready(function() {
	for (var i = 0; i < classes.length; i++) {
		if (classes[i].ngrade == $("#selectngrade option:selected" ).attr("value")){
			$("<option>").val(classes[i].id).text(classes[i].classname).appendTo('#selectclass');
		}
	};
});




if($("#user_jpclasssubmit").text() != "None"){
	$(document).ready(function() {
		$("#selectclass option[value={{ user_jpclasssubmit.jpclass.id }}]").attr('selected', 'selected');
	});
}



$("#selectngrade").change(function(){
	$("#selectngrade option:selected" ).each(function() {
		$("#selectclass option").remove();
		for (var i = 0; i < classes.length; i++) {
			if (classes[i].ngrade == $("#selectngrade option:selected" ).attr("value")){
				$("<option>").val(classes[i].id).text(classes[i].classname).appendTo('#selectclass');
			}
		};

	});


});



$("#changebtn").click(function(){
	$("#resultrow").css('display', 'none');
	$("#selectrow").css('display', 'block');
});

$("#cancelbtn").click(function(){
	$("#resultrow").css('display', 'block');
	$("#selectrow").css('display', 'none');
});


</script>
{% endblock %}