src/score/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from score import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'survey.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name="index"),
    url(r'^submit/$',views.submit,name="submit"),
    url(r'^result/$',views.result,name="result"),
)

src/stationary/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from stationary import views


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'survey.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name="index"),
    url(r'^submit/$',views.submit,name="submit"),
    url(r'^result/$',views.result,name="result"),
)

src/survey/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'survey.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^stationary/', include('stationary.urls',namespace='stationary')),
    url(r'^account/', include('account.urls',namespace='account')),
    url(r'^japanese/', include('japanese.urls',namespace='japanese')),
    )

src/stationary/models.py
#-*- coding: UTF-8 -*-
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.
class StationaryType(models.Model):
    name=models.CharField(max_length=100)
    remark=models.CharField(max_length=100,default=None)
    
    def __unicode__(self):
        return self.name
    
    def sum(self):
        num=0
        for choice in self.choice_set.all():
            num= num+choice.num
        return num
    
class Choice(models.Model):
    user=models.ForeignKey(User)
    stationary_type=models.ForeignKey(StationaryType)
    num=models.IntegerField(default=0)
    
    def __unicode__(self):
        return str(self.id)
    
    def get_user_name(self):
        return self.user.username
    
    def get_user_stationaryname(self):
        return self.stationary_type.name
    
    def get_user_stationarynum(self):
        return self.stationary_type.num

src/stationary/views.py
#-*- coding: UTF-8 -*-
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from stationary.models import StationaryType, Choice


# Create your views here.
def index(request):
    context = {'user':request.user,'stationarytype':StationaryType.objects.all()}
    return render(request, 'stationary/index.html', context)

def result(request):
    return render(request,'stationary/result.html',{'user_list':User.objects.all(),'stationary_list':StationaryType.objects.all()})


def submit(request):
    stationary_num=[]
    try:
        for i in range(1,StationaryType.objects.count()+1):
            stationary_num.append(request.POST['stationary_num'+str(i)])
    except (KeyError, StationaryType.DoesNotExist):
        return render(request, 'stationary/index.html',{
            'error_message': "You didn't input all choices.",
           })
    else:
#         choice=Choice(user=request.user,stationary_type=None,num=stationary_num)
#         choice.save()
        u=request.user
        i=0
        for stationarytype in StationaryType.objects.all():
            u.choice_set.create(stationary_type=stationarytype,num=int(stationary_num[i]))
            i=i+1
        return HttpResponseRedirect(reverse('stationary:result'))
    

src/stationary/templates/stationary/index.html
{% extends "stationary/base.html" %}
{% block title %}Insert title here{% endblock %}
{% block content %}
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<form action="{% url 'stationary:submit' %}" method="post">
	{% csrf_token %}
	{% for stationary in stationarytype %}
		{{ forloop.counter }}
		<label for="stationary{{ forloop.counter }}">{{ stationary.name }}</label>
    	<input type="text" name="stationary_num{{ forloop.counter }}" id="stationary{{ forloop.counter }}" value="" size="4" /> <br />
	{% endfor %}
	<input type="submit" value="Submit" />
	</form>
{% endblock %}

src/stationary/templates/stationary/result.html
{% extends "stationary/base.html" %} 
{% block title %}Insert title here{% endblock %} 
{% block content %}

<table border="1">
	<tr>
		<th></th> 
		{% for stationary in stationary_list %}
		<th>{{stationary.name}}</th> 
		{% endfor %}
	</tr>
	{% for user in user_list %}
	<tr>
		<td>{{user.username}}</td> 
		{% if not user.choice_set.all %}
			{% for stationary in stationary_list %}
				<td>{{ 0 }}</td> 
			{% endfor %}		
		{% else %}
			{% for choice in user.choice_set.all %}
				<td>{{choice.num}}</td> 
			{% endfor %}
		{% endif %}
	</tr>
	{% endfor %}
</table>
{% endblock %}